src/main/java/org/silsagusi/joonggaemoa/domain/agent/entity/Agent.java
src/main/java/org/silsagusi/joonggaemoa/domain/agent/entity/AgentCustomer.java
src/main/java/org/silsagusi/joonggaemoa/domain/agent/repository/AgentCustomerRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/agent/repository/AgentRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/consultation/entity/Consultation.java
src/main/java/org/silsagusi/joonggaemoa/domain/consultation/repository/ConsultationRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/contract/entity/Contract.java
src/main/java/org/silsagusi/joonggaemoa/domain/contract/entity/ContractDetail.java
src/main/java/org/silsagusi/joonggaemoa/domain/contract/repository/ContractDetailRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/contract/repository/ContractRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/customer/entity/Customer.java
src/main/java/org/silsagusi/joonggaemoa/domain/customer/repository/CustomerRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/Message.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/MessageLog.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/MessageTemplate.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/MessageLogRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/MessageRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/MessageTemplateRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/property/entity/Complex.java
src/main/java/org/silsagusi/joonggaemoa/domain/property/entity/Property.java
src/main/java/org/silsagusi/joonggaemoa/domain/property/entity/ScrapedProperty.java
src/main/java/org/silsagusi/joonggaemoa/domain/property/repository/ComplexRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/property/repository/PropertyRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/property/repository/ScrapedPropertyRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/entity/Answer.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/entity/Question.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/entity/Survey.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/repository/AnswerRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/repository/QuestionRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/repository/SurveyRepository.java

패키지 구조, 응답 구조, 엔티티, 레포지토리 생성
Resolves: #2 
어떤 변경 사항이 있나요?

[#2] feat: 엔티티, 레포지토리 생성

---

.github/workflows/cicd.yml
Dockerfile
build.gradle
src/main/resources/application.yml

1. CI build error 해결
* ./gradlew build -> /gradlew build -x test
* 테스트 코드가 아직 없어서 build 오류가 나는 것을 code test없이 build 하는 설정으로 바꾸어 해결했습니다
2. CD deploy 실행 설정 추가
다음 실행 모두 테스트하여 확인했습니다
* 돌아가는 컨테이너가 존재하지 않을 때, 새로운 컨테이너 실행 확인
* 기존에 돌아가는 컨테이너가 있을 때, 기존 컨테이너 종료 후 새로운 컨테이너 실행 확인
*  새로운 컨테이너 배포 실패 시, 기존 컨테이너 재실행 확인
3. github setting 추가
* github actions에서 ci/cd 실패 시, PR/merge가 안 되도록 변경해뒀습니다
Resolves: #1 
어떤 변경 사항이 있나요?

Feature 6 fixcicd

---

src/main/java/org/silsagusi/joonggaemoa/global/auth/SecurityConfig.java

Authorization 헤더 추가를 위한 설정파일 수정
Resolves: #3 
어떤 변경 사항이 있나요?

[#3] fix: Authorization 헤더 추가를 위한 설정파일 수정

---

build.gradle
src/main/java/org/silsagusi/joonggaemoa/domain/customer/controller/CustomerController.java
src/main/java/org/silsagusi/joonggaemoa/domain/customer/controller/dto/CreateCustomerRequestDto.java
src/main/java/org/silsagusi/joonggaemoa/domain/customer/service/CustomerCommand.java
src/main/java/org/silsagusi/joonggaemoa/domain/customer/service/CustomerService.java
src/main/java/org/silsagusi/joonggaemoa/global/api/GlobalExceptionHandler.java
src/main/java/org/silsagusi/joonggaemoa/global/api/ResponseInterceptor.java
src/main/java/org/silsagusi/joonggaemoa/global/api/exception/ErrorCode.java

개인 고객 등록, 엑셀 파일 고객 등록 기능 추가했습니다
Resolves: #10
어떤 변경 사항이 있나요?

[#10] feat: 고객 등록 기능 추가

---

src/main/java/org/silsagusi/joonggaemoa/domain/agent/service/AgentService.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/SurveyResponse.java
src/main/java/org/silsagusi/joonggaemoa/global/auth/jwt/JwtProvider.java

FE와 연동 중 수정할 부분이 보여서 수정하였습니다
Resolves: #23
어떤 변경 사항이 있나요?

[#23] fix: agent 가입 수정, survery response 수정

---

src/main/java/org/silsagusi/joonggaemoa/domain/consultation/contorller/ConsultationApiController.java
src/main/java/org/silsagusi/joonggaemoa/domain/consultation/contorller/dto/CreateConsultationRequest.java
src/main/java/org/silsagusi/joonggaemoa/domain/consultation/entity/Consultation.java
src/main/java/org/silsagusi/joonggaemoa/domain/consultation/service/ConsultationService.java
src/main/java/org/silsagusi/joonggaemoa/global/auth/SecurityConfig.java

상담 생성을 예약으로 수정
Resolves: #28
어떤 변경 사항이 있나요?

Feature 28 상담생성수정

---

src/main/java/org/silsagusi/joonggaemoa/domain/survey/repository/QuestionRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/SurveyService.java

surveyDelete, update 버그 수정
* update시 전부 지우고, 전부 다시 등록하게 수정
Resolves: #32
어떤 변경 사항이 있나요?

[#32] fix: surveyDelete, Update bug fix

---

src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/MessageController.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/Category.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/MessageRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/service/MessageService.java
src/main/java/org/silsagusi/joonggaemoa/global/batch/SmsBatchJogConfig.java
src/main/java/org/silsagusi/joonggaemoa/global/config/ScheduleConfig.java

프론트와 연동을 위한 응답 구조 변경
문자 발송을 위한 스케줄러 주기 조정
Resolves: #23 
어떤 변경 사항이 있나요?

[#23] fix: message response 수정

---

.github/workflows/cicd.yml
src/main/resources/application.yml

* 브랜치 전략 변경하여, main이 아닌 release에서 CD하도록 변경하였습니다
* CD 수정
* 도커에 중복된 이름이 있을 때, 컨테이너 생성이 안되는 오류처리가 안 되어있어서 예외처리 추가했습니다
* 컨테이너 이름변경 실패 시에도 success로 처리되는 오류가 있어서, 실패되도록 변경했습니다  
Resolves: #30
어떤 변경 사항이 있나요?

[#30] fix: cd main에서 release로 변경

---

src/main/java/org/silsagusi/joonggaemoa/global/BaseEntity.java
src/main/resources/application.yml

base entity의 코드가 JPA만 사용하고 있어서 Spring Data JPA의 코드로 변경하였습니다
@PrePersist와 @PreUpdate가 @EntityListner안에 포함되어 있습니다.
application.yml의 프로필의 기본설정이 배포로 되어있어서 로컬로 수정하였습니다.
Resolves: #39 
어떤 변경 사항이 있나요?

[#39] FIX: base entity 수정

---

src/main/java/org/silsagusi/joonggaemoa/global/auth/SecurityConfig.java

프론트엔드 배포 주소 추가
security config에 CORS 허용을 위해 배포주소를 추가하였습니다
Resolves: #23 
어떤 변경 사항이 있나요?

[#23] FEAT: 프론트엔드 배포 주소 추가

---

src/main/java/org/silsagusi/joonggaemoa/domain/agent/entity/Agent.java
src/main/java/org/silsagusi/joonggaemoa/domain/consultation/entity/Consultation.java
src/main/java/org/silsagusi/joonggaemoa/domain/contract/entity/Contract.java
src/main/java/org/silsagusi/joonggaemoa/domain/customer/entity/Customer.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/Message.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/MessageTemplate.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/ReservedMessage.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/entity/Answer.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/entity/Question.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/entity/QuestionAnswerPair.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/entity/Survey.java

@NoArgsConstructor에 access level을 protected로 수정하였습니다
Entity에 Enum타입의 필드에 @Enumerated(EnumType.STRING)을 추가하였습니다
Resolves: #(Isuue Number)
어떤 변경 사항이 있나요?

[#41] REFACTOR: 1차 리팩토링

---

src/main/resources/application.yml

redis 연동 시 host를 찾지 못하는 문제가 생겨, local/prod에서 각각 localhost/ec2를 참조하도록 host 설정을 변경했습니다
Resolves: #46
어떤 변경 사항이 있나요?

[#46] FIX: redis host 변경

---

build.gradle
src/main/java/org/silsagusi/joonggaemoa/global/config/SwaggerConfig.java
src/main/resources/application.yml

- springdoc 최신 버전으로 변경하여 swagger 에러 해결
- Authorize 버튼 눌러서 토큰 추가할 수 있게 했습니다. 
- /swagger-ui uri 설정 추가했습니다.
Resolves: #56
어떤 변경 사항이 있나요?

[#56] FEAT: swagger에 jwt 인증 기능 추가

---

src/main/java/org/silsagusi/joonggaemoa/domain/contract/controller/ContractController.java
src/main/java/org/silsagusi/joonggaemoa/domain/contract/controller/dto/ContractDetailDto.java
src/main/java/org/silsagusi/joonggaemoa/domain/contract/controller/dto/ContractDto.java
src/main/java/org/silsagusi/joonggaemoa/domain/contract/service/command/ContractCommand.java

ContractDto
- Id -> Name으로 수정해서 페이지에서 이름 보이게 수정
ContractDetailDto
- ContractDto에 연락처, 이메일 추가
ContractCommand
- 계약 관리 api에 이름, 연락처, 이메일 추가하기 위해 수정
Resolves: #55
어떤 변경 사항이 있나요?

[#55] FEATURE: 계약 목록, 상세 dto 수정

---

src/main/java/org/silsagusi/joonggaemoa/domain/agent/service/AgentService.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/MessageController.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/MessageTemplateController.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/MessageDto.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/MessageTemplateDto.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/MessageTemplateUpdateRequest.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/ReservedMessageDto.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/ReservedMessageUpdateRequest.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/MessageTemplate.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/entity/ReservedMessage.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/MessageTemplateRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/service/MessageService.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/service/MessageTemplateService.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/service/command/MessageCommand.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/service/command/MessageTemplateCommand.java
src/main/java/org/silsagusi/joonggaemoa/global/auth/filter/JwtAuthenticationFilter.java
src/main/java/org/silsagusi/joonggaemoa/global/auth/jwt/JwtProvider.java
src/main/java/org/silsagusi/joonggaemoa/global/auth/jwt/RefreshTokenController.java
src/main/java/org/silsagusi/joonggaemoa/global/auth/jwt/RefreshTokenService.java

문자 api 수정
* 수정 api -> 삭제 api 로 수정했습니다
* 템플릿에 카테고리를 제목으로 수정했습니다.
Resolves: #54 
어떤 변경 사항이 있나요?

[#54] FIX: 문자api, 문자 템플릿 api 수정

---

src/main/java/org/silsagusi/joonggaemoa/domain/agent/controller/AgentController.java
src/main/java/org/silsagusi/joonggaemoa/domain/agent/controller/dto/AgentDto.java
src/main/java/org/silsagusi/joonggaemoa/domain/agent/controller/dto/AgentUpdateRequest.java
src/main/java/org/silsagusi/joonggaemoa/domain/agent/entity/Agent.java
src/main/java/org/silsagusi/joonggaemoa/domain/agent/service/AgentService.java
src/main/java/org/silsagusi/joonggaemoa/domain/agent/service/command/AgentCommand.java

중개사의 마이페이지를 위한 유저 정보 조회, 유저 정보 수정 api 구현하였습니다.
Resolves: #63 
어떤 변경 사항이 있나요?

[#63] FEAT: 유저 정보 조회,수정 api 구현

---

src/main/java/org/silsagusi/joonggaemoa/domain/agent/repository/AgentRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/agent/service/AgentService.java
src/main/java/org/silsagusi/joonggaemoa/global/auth/filter/JwtAuthenticationFilter.java

회원가입할 때 이미 있는 데이터면 에러 응답 반환
로그인 실패시 에러 응답 반환
Resolves: #65
어떤 변경 사항이 있나요?

[#65] FEAT: 회원가입, 로그인 예외처리

---

src/main/java/org/silsagusi/joonggaemoa/JoonggaeMoaApplication.java
src/main/java/org/silsagusi/joonggaemoa/global/config/ScheduleConfig.java

@EnableScheduling위치를 JoonggaeMoaApplication에서 ScheduleConfig로 옮겼습니다.
Resolves: #69 
어떤 변경 사항이 있나요?

[#69] FIX: @EnableScheduling 위치 수정

---

src/main/java/org/silsagusi/joonggaemoa/domain/agent/repository/AgentRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/agent/service/AgentService.java
src/main/java/org/silsagusi/joonggaemoa/global/api/ApiResponse.java

회원 가입 중복 검증 수정했습니다.
AgentRepository에서 existsByUsername(String username)을 @Query를 사용하도록 변경했습니다.
Resolves: #71 
어떤 변경 사항이 있나요?

[#71] FIX: 회원 가입 중복 검증 수정

---

src/main/java/org/silsagusi/joonggaemoa/domain/customer/service/CustomerService.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/SurveyController.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/QuestionDto.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/SurveyDto.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/entity/Survey.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/repository/SurveyRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/SurveyService.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/command/QuestionCommand.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/command/SurveyCommand.java
src/main/java/org/silsagusi/joonggaemoa/request/naverland/scheduler/NaverLandScheduler.java

설문 response, 설문 응답 response에 createdAt 추가했습니다
설문 응답 페이지는 누구나 접근이 가능해서 id를 Long 타입에서 String타입으로 바꾸고 UUID로 변경하였습니다
Survey의 description 필드를 필수값이 아니어도 입력가능하게 변경하였습니다
Resolves: #80 
어떤 변경 사항이 있나요?

[#80] FIX: 설문 api 수정

---

src/main/java/org/silsagusi/joonggaemoa/domain/notify/controller/NotificationController.java
src/main/java/org/silsagusi/joonggaemoa/domain/notify/controller/dto/NotificationDto.java
src/main/java/org/silsagusi/joonggaemoa/domain/notify/service/NotificationService.java
src/main/java/org/silsagusi/joonggaemoa/domain/notify/service/command/NotificationCommand.java

프론트엔드 알림 기능 설정하면서
* response 데이터에 isRead 추가했습니다
* pathParam을 RequestParam 형식으로 받도록 변경했습니다
Resolves: #84
어떤 변경 사항이 있나요?

[#84] FEATURE: isRead 추가 및 request 방식 변경

---

src/main/java/org/silsagusi/joonggaemoa/global/config/ScheduleConfig.java
src/main/java/org/silsagusi/joonggaemoa/request/naverland/scheduler/NaverLandScheduler.java

* 매물 스케줄링 주석 제거했습니다
* 각 스케줄링은 따로 실행하도록 분리했습니다
Resolves: #86
어떤 변경 사항이 있나요?

[#86] REFACTOR: 스케줄링 리팩토링

---

src/main/java/org/silsagusi/joonggaemoa/global/config/ScheduleConfig.java

매물을 크롤링 하는 스케줄러가 시작될 때, 길이가 길어서 다른 스케줄러가 계속 뒤로 밀려 우선순위가 낮아져 starvation 문제가 생겨 스케줄링 비동기 처리했습니다
Resolves: #89
어떤 변경 사항이 있나요?

[#89] REFACTOR: 스케줄러 비동기 처리

---

src/main/java/org/silsagusi/joonggaemoa/domain/message/controller/dto/MessageDto.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/MessageRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/service/MessageService.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/service/command/MessageCommand.java

문자 응답값에 sendAt 추가
문자 내용에 ${이름}이 있는 경우 고객의 이름으로 교체한 뒤 저장
Resolves: #99 
어떤 변경 사항이 있나요?

[#99] FIX: 문자 에러 수정

---

src/main/java/org/silsagusi/joonggaemoa/domain/article/controller/ArticleController.java
src/main/java/org/silsagusi/joonggaemoa/domain/article/service/RegionService.java
src/main/java/org/silsagusi/joonggaemoa/domain/article/service/dto/RegionResponse.java

이 풀 리퀘스트는 `ArticleController`에 새로운 `RegionService`를 도입하고 지역 데이터를 검색할 수 있는 새로운 엔드포인트를 추가합니다. 가장 중요한 변경 사항으로는 `RegionService` 클래스 추가, `RegionResponse` DTO 생성, 새 서비스와 엔드포인트를 통합하기 위한 `ArticleController` 수정이 있습니다.
* [`src/main/java/org/silsagusi/joonggaemoa/domain/article/service/RegionService.java`](diffhunk://#diff-95620f13ce19247985e51a7adef65684e738723ac6cba4f5b28a5fed45c47ee2R1-R21): 지역 관련 작업을 처리하는 `RegionService` 클래스를 추가했습니다.
* [`src/main/java/org/silsagusi/joonggaemoa/domain/article/service/dto/RegionResponse.java`](diffhunk://#diff-f961e5395ab2cfdf74b6129a8a898c0206306c9228457915a44db26ccec4851fR1-R25): 지역 데이터를 표현하기 위해 `RegionResponse` DTO를 생성했습니다.
* `src/main/java/org/silsagusi/joonggaemoa/domain/article/controller/ArticleController.java`: 
* Imported `RegionService` and …

[#102] FEAT: 모든 지역을 조회하는 RegionService 및 엔드포인트 추가

---

src/main/java/org/silsagusi/joonggaemoa/domain/consultation/entity/Consultation.java
src/main/java/org/silsagusi/joonggaemoa/domain/customer/service/CustomerService.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/SurveyController.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/controller/dto/AnswerDto.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/entity/Answer.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/SurveyService.java
src/main/java/org/silsagusi/joonggaemoa/domain/survey/service/command/AnswerCommand.java

설문 응답에 상담 여부를 묻고 동의한다면 상담 날짜도 받도록 수정하였습니다
신규 고객이면 추가하도록 수정하였습니다
Resolves: #103
어떤 변경 사항이 있나요?

[#103] FEAT: 설문 응답에 상담 여부 추가

---

src/main/java/org/silsagusi/joonggaemoa/domain/contract/controller/ContractController.java
src/main/java/org/silsagusi/joonggaemoa/domain/contract/controller/dto/ContractDetailDto.java
src/main/java/org/silsagusi/joonggaemoa/domain/contract/controller/dto/ContractDto.java
src/main/java/org/silsagusi/joonggaemoa/domain/contract/entity/Contract.java
src/main/java/org/silsagusi/joonggaemoa/domain/contract/repository/ContractRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/contract/service/ContractService.java
src/main/java/org/silsagusi/joonggaemoa/domain/contract/service/command/ContractCommand.java

Contract id타입 string으로 변경
Resolves: #104
어떤 변경 사항이 있나요?

[#104] FIX: contract id타입 string으로 변경

---

src/main/java/org/silsagusi/joonggaemoa/domain/customer/repository/CustomerRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/customer/service/CustomerService.java
src/main/java/org/silsagusi/joonggaemoa/global/api/GlobalExceptionHandler.java

고객 등록 시 이메일, 전화번호 중복 검증 로직 추가
Resolves: #107
어떤 변경 사항이 있나요?

[#107] FEATURE: 고객 등록 시 이메일, 전화번호 중복 검증 로직 추가

---

src/main/java/org/silsagusi/joonggaemoa/domain/agent/entity/Agent.java
src/main/java/org/silsagusi/joonggaemoa/domain/agent/repository/AgentRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/agent/service/AgentService.java

entity에서 unique로 error handling 시, 프론트에서 어떤 값이 중복되어 오류가 났는지 구분에 안돼서, unique 삭제하고 service에 중복 검증 로직 추가했습니다
Resolves: #109
어떤 변경 사항이 있나요?

[#109] FEAT: agent username, phone, email 중복 검증 로직 추가

---

src/main/java/org/silsagusi/joonggaemoa/domain/article/controller/ArticleController.java
src/main/java/org/silsagusi/joonggaemoa/domain/article/entity/Article.java
src/main/java/org/silsagusi/joonggaemoa/domain/article/service/ArticleService.java
src/main/java/org/silsagusi/joonggaemoa/domain/article/service/dto/ArticleResponse.java

매물의 가격 범위 검색 기능이 동작하지 않아 수정하였습니다
String으로 저장되어있던 Price 필드를 Integer로 수정하였습니다
Resolves: #111 
어떤 변경 사항이 있나요?

[#111] FIX: 매물 가격 범위 검색 기능 수정

---

src/main/java/org/silsagusi/joonggaemoa/domain/customer/service/CustomerService.java

설문 응답 제출왔을 때 신규 고객이면 등록되도록 수정했습니다
Resolves: #114 
어떤 변경 사항이 있나요?

[#114] FIX: 고객 생성 로직 수정

---

src/main/java/org/silsagusi/joonggaemoa/domain/message/repository/MessageRepository.java
src/main/java/org/silsagusi/joonggaemoa/domain/message/service/MessageService.java

메세지 조회 메소드 수정했습니다
Resolves: #116 
어떤 변경 사항이 있나요?

[#116] FIX: 메세지 조회 메소드 수정

---

src/main/java/org/silsagusi/joonggaemoa/global/auth/SecurityConfig.java

* 프론트 배포 주소 변경하면서, cors 설정 주소 변경
* authorizeHttpRequests에permit all을 지우고 AUTH 처리하는 주석 제거
Resolves: #118
어떤 변경 사항이 있나요?

[#118] FEATURE: SecurityConfig 설정 변경

---

src/main/java/org/silsagusi/joonggaemoa/global/config/DataDBConfig.java
src/main/resources/application.yml

환경 유지를 위해 Hibernate DDL 설정을 update로 변경했습니다
Resolves: #127 
어떤 변경 사항이 있나요?

[#127] CHORE: ddl설정 update로 변경

---

api/src/main/java/org/silsagusi/api/message/application/dto/MessageDto.java
api/src/main/java/org/silsagusi/api/survey/application/dto/AnswerDto.java
api/src/main/java/org/silsagusi/api/survey/application/dto/SurveyDto.java
core/src/main/java/org/silsagusi/core/config/DataDBConfig.java
core/src/main/java/org/silsagusi/core/domain/BaseEntity.java
core/src/main/java/org/silsagusi/core/domain/message/entity/Message.java
core/src/main/java/org/silsagusi/core/domain/notification/entity/Notification.java
core/src/main/java/org/silsagusi/core/domain/survey/entity/Answer.java
core/src/main/java/org/silsagusi/core/domain/survey/entity/Survey.java

base entity의 createdAt과 updatedAt이 String으로 되어있어서 LocalDateTime으로 변경하였습니다
Resolves: #141 
어떤 변경 사항이 있나요?

[#141] FIX: base entity 수정

---

api/src/main/java/org/silsagusi/api/agent/application/dto/AgentDto.java
api/src/main/java/org/silsagusi/api/agent/application/dto/UsernameDto.java
api/src/main/java/org/silsagusi/api/agent/controller/AgentController.java
api/src/main/java/org/silsagusi/api/consultation/application/dto/ConsultationDto.java
api/src/main/java/org/silsagusi/api/contract/application/dto/ContractDto.java
api/src/main/java/org/silsagusi/api/customer/application/dto/CustomerDto.java
api/src/main/java/org/silsagusi/api/message/application/dto/MessageDto.java
api/src/main/java/org/silsagusi/api/message/application/dto/MessageTemplateDto.java
api/src/main/java/org/silsagusi/api/survey/application/dto/AnswerDto.java
api/src/main/java/org/silsagusi/api/survey/application/dto/QuestionDto.java
api/src/main/java/org/silsagusi/api/survey/application/dto/SurveyDto.java
core/src/main/java/org/silsagusi/core/customResponse/GlobalExceptionHandler.java

스웨거와 @RestControllerAdvice가 충돌나서 @Hidden을 달아서 해결하였습니다
로그인 api가 안보여서 이것도 api문서용으로 더미 엔드포인트를 생성하였습니다
dto에 @Schema를 달아서 명시적으로 변경하였습니다
Resolves: #148 
어떤 변경 사항이 있나요?

[#148] REFACTOR: 스웨거 연동

---

api/src/main/java/org/silsagusi/api/agent/application/AgentService.java
api/src/main/java/org/silsagusi/api/agent/infrastructure/AgentDataProvider.java
api/src/main/java/org/silsagusi/api/agent/infrastructure/AgentValidator.java
api/src/main/java/org/silsagusi/api/consultation/application/ConsultationService.java
api/src/main/java/org/silsagusi/api/consultation/infrastructure/ConsultationDataProvider.java
api/src/main/java/org/silsagusi/api/consultation/infrastructure/ConsultationValidator.java
api/src/main/java/org/silsagusi/api/contract/application/ContractService.java
api/src/main/java/org/silsagusi/api/contract/infrastructure/ContractDataProvider.java
api/src/main/java/org/silsagusi/api/contract/infrastructure/ContractValidator.java
api/src/main/java/org/silsagusi/api/customer/application/CustomerService.java
api/src/main/java/org/silsagusi/api/customer/infrastructure/CustomerDataProvider.java
api/src/main/java/org/silsagusi/api/customer/infrastructure/CustomerValidator.java
api/src/main/java/org/silsagusi/api/message/application/service/MessageService.java
api/src/main/java/org/silsagusi/api/message/application/service/MessageTemplateService.java
api/src/main/java/org/silsagusi/api/message/infrastructure/dataProvider/MessageDataProvider.java
api/src/main/java/org/silsagusi/api/message/infrastructure/dataProvider/MessageTemplateDataProvider.java
api/src/main/java/org/silsagusi/api/message/infrastructure/validator/MessageTemplateValidator.java
api/src/main/java/org/silsagusi/api/message/infrastructure/validator/MessageValidator.java
api/src/main/java/org/silsagusi/api/survey/application/SurveyService.java
api/src/main/java/org/silsagusi/api/survey/infrastructure/dataProvider/SurveyDataProvider.java
api/src/main/java/org/silsagusi/api/survey/infrastructure/validator/SurveyValidator.java

data provider에 validator역할을 하는 메서드도 포함되어 있어서 역할 분리를 위해 validator를 구현했습니다
Resolves: #155 
어떤 변경 사항이 있나요?

[#155] REFACTOR: validator 구현

---

api/src/main/java/org/silsagusi/api/consultation/application/ConsultationMapper.java
api/src/main/java/org/silsagusi/api/consultation/application/dto/UpdateConsultationRequest.java
api/src/main/java/org/silsagusi/api/consultation/infrastructure/ConsultationDataProvider.java
api/src/main/java/org/silsagusi/api/customer/infrastructure/CustomerDataProvider.java
api/src/main/java/org/silsagusi/api/message/application/service/MessageTemplateService.java
api/src/main/java/org/silsagusi/api/message/infrastructure/dataProvider/MessageTemplateDataProvider.java
api/src/main/java/org/silsagusi/api/survey/infrastructure/dataProvider/SurveyDataProvider.java
core/src/main/java/org/silsagusi/core/domain/consultation/entity/Consultation.java
core/src/main/java/org/silsagusi/core/domain/customer/entity/Customer.java
core/src/main/java/org/silsagusi/core/domain/message/entity/Message.java
core/src/main/java/org/silsagusi/core/domain/message/entity/MessageTemplate.java
core/src/main/java/org/silsagusi/core/domain/survey/entity/Question.java
core/src/main/java/org/silsagusi/core/domain/survey/entity/QuestionAnswerPair.java
core/src/main/java/org/silsagusi/core/domain/survey/entity/Survey.java

dynamic update 적용했습니다
Resolves: #68
어떤 변경 사항이 있나요?

[#68] REFACTOR: dynamic update 적용

---

api/src/main/java/org/silsagusi/api/agent/application/AgentMapper.java
api/src/main/java/org/silsagusi/api/agent/infrastructure/AgentDataProvider.java
api/src/main/java/org/silsagusi/api/agent/infrastructure/AgentRepository.java
api/src/main/java/org/silsagusi/api/agent/infrastructure/AgentValidator.java
api/src/main/java/org/silsagusi/api/auth/userDetails/CustomUserDetailsService.java
api/src/main/java/org/silsagusi/api/consultation/infrastructure/ConsultationDataProvider.java
api/src/main/java/org/silsagusi/api/consultation/infrastructure/ConsultationRepository.java
api/src/main/java/org/silsagusi/api/contract/infrastructure/ContractDataProvider.java
api/src/main/java/org/silsagusi/api/contract/infrastructure/ContractRepository.java
api/src/main/java/org/silsagusi/api/customer/infrastructure/CustomerDataProvider.java
api/src/main/java/org/silsagusi/api/customer/infrastructure/CustomerRepository.java
api/src/main/java/org/silsagusi/api/customer/infrastructure/CustomerValidator.java
api/src/main/java/org/silsagusi/api/message/infrastructure/dataProvider/MessageDataProvider.java
api/src/main/java/org/silsagusi/api/message/infrastructure/dataProvider/MessageTemplateDataProvider.java
api/src/main/java/org/silsagusi/api/message/infrastructure/repository/MessageRepository.java
api/src/main/java/org/silsagusi/api/message/infrastructure/repository/MessageTemplateRepository.java
api/src/main/java/org/silsagusi/api/survey/infrastructure/dataProvider/SurveyDataProvider.java
api/src/main/java/org/silsagusi/api/survey/infrastructure/repository/AnswerRepository.java
api/src/main/java/org/silsagusi/api/survey/infrastructure/repository/SurveyRepository.java
core/src/main/java/org/silsagusi/core/domain/BaseEntity.java
core/src/main/java/org/silsagusi/core/domain/agent/Agent.java
core/src/main/java/org/silsagusi/core/domain/consultation/entity/Consultation.java
core/src/main/java/org/silsagusi/core/domain/contract/entity/Contract.java
core/src/main/java/org/silsagusi/core/domain/customer/entity/Customer.java
core/src/main/java/org/silsagusi/core/domain/message/entity/MessageTemplate.java
core/src/main/java/org/silsagusi/core/domain/survey/entity/Question.java
core/src/main/java/org/silsagusi/core/domain/survey/entity/QuestionAnswerPair.java

프로젝트의 모든 entity에 대해 Soft Delete 기능을 적용하여 데이터를 삭제할 때 실제로 데이터를 삭제하는 대신, 삭제 상태를 나타내는 필드를 추가하여 삭제를 처리할 수 있도록 개선하였습니다
Resolves: #159
어떤 변경 사항이 있나요?

[#159] REFACTOR: soft delete 적용

---

api/src/main/java/org/silsagusi/api/config/RedisConfig.java
api/src/main/java/org/silsagusi/api/config/S3Config.java
api/src/main/java/org/silsagusi/api/config/SwaggerConfig.java
batch/src/main/java/org/silsagusi/batch/config/CacheConfig.java
batch/src/main/java/org/silsagusi/batch/config/WebClientConfig.java

api 모듈에서만 쓰거나 batch 모듈에서만 쓰는 config 클래스들을 각 모듈로 이동하였습니다
Resolves: #166 
어떤 변경 사항이 있나요?

[#166] REFACTOR: config 각 모듈로 이동

---

api/src/main/java/org/silsagusi/api/auth/SecurityConfig.java
api/src/main/java/org/silsagusi/api/config/ScheduleConfig.java
api/src/main/java/org/silsagusi/api/notification/application/NotificationMapper.java
api/src/main/java/org/silsagusi/api/notification/application/NotificationService.java
api/src/main/java/org/silsagusi/api/notification/application/dto/NotificationDto.java
api/src/main/java/org/silsagusi/api/notification/controller/NotificationController.java
api/src/main/java/org/silsagusi/api/notification/infrastructure/EmitterRepository.java
api/src/main/java/org/silsagusi/api/notification/infrastructure/NotificationDataProvider.java
api/src/main/java/org/silsagusi/api/notification/infrastructure/NotificationRepository.java
api/src/main/java/org/silsagusi/api/survey/application/SurveyService.java
core/src/main/java/org/silsagusi/core/domain/notification/entity/NotificationType.java

알림 기능 제대로 작동하도록 수정했습니다
Resolves: #171
어떤 변경 사항이 있나요?

[#171] FEATURE: 알림 기능

---

api/src/main/java/org/silsagusi/api/consultation/application/ConsultationMapper.java
api/src/main/java/org/silsagusi/api/consultation/application/ConsultationService.java
api/src/main/java/org/silsagusi/api/consultation/application/dto/ConsultationDto.java
api/src/main/java/org/silsagusi/api/consultation/application/dto/ConsultationHistoryDto.java
api/src/main/java/org/silsagusi/api/consultation/application/dto/UpdateConsultationRequest.java
api/src/main/java/org/silsagusi/api/consultation/controller/ConsultationController.java
api/src/main/java/org/silsagusi/api/consultation/infrastructure/ConsultationDataProvider.java
api/src/main/java/org/silsagusi/api/consultation/infrastructure/ConsultationRepository.java
api/src/main/java/org/silsagusi/api/survey/application/SurveyService.java
core/src/main/java/org/silsagusi/core/domain/consultation/command/UpdateConsultationCommand.java
core/src/main/java/org/silsagusi/core/domain/consultation/entity/Consultation.java
core/src/main/java/org/silsagusi/core/domain/customer/entity/Customer.java

상담 페이지에서 연결되는 느낌을 주고자 이전 상담들과 연결지어 보여주기 위해 상담 히스토리 api를 구현하였습니다
Resolves: #170 
어떤 변경 사항이 있나요?

[#170] FEAT: 170 상담 히스토리 api

---

api/src/main/java/org/silsagusi/api/contract/application/ContractMapper.java
api/src/main/java/org/silsagusi/api/contract/application/dto/ContractDetailDto.java
api/src/main/java/org/silsagusi/api/contract/application/dto/ContractDto.java
api/src/main/java/org/silsagusi/api/contract/infrastructure/ContractRepository.java
core/src/main/java/org/silsagusi/core/domain/contract/entity/Contract.java
core/src/main/java/org/silsagusi/core/domain/contract/info/ContractDetailInfo.java
core/src/main/java/org/silsagusi/core/domain/contract/info/ContractInfo.java

계약 entity의 createdAT을 startedAt으로 변경하고 baseentity를 상속받도록 변경했습니다
Resolves: #176
어떤 변경 사항이 있나요?

[#176] FIX: 계약 - createdAT을 startedAt으로 변경

---

api/src/main/java/org/silsagusi/api/config/SwaggerConfig.java

스웨거는 기본적으로 http가 적용되어있어서 https를 적용했습니다
Resolves: #189 
어떤 변경 사항이 있나요?

[#189] FIX: 스웨거 https 적용

---

api/src/main/java/org/silsagusi/api/inquiry/application/dto/InquiryDto.java
api/src/main/java/org/silsagusi/api/inquiry/application/mapper/InquiryMapper.java
api/src/main/java/org/silsagusi/api/inquiry/application/validator/InquiryValidator.java
api/src/main/java/org/silsagusi/api/inquiry/infrastructure/dataprovider/InquiryDataProvider.java
core/src/main/java/org/silsagusi/core/domain/inquiry/command/UpdateInquiryCommand.java
core/src/main/java/org/silsagusi/core/domain/inquiry/entity/Inquiry.java

- 의존성 주입 시 final이 아니어서 생기는 오류 -> final 추가
- 문의글 update 시 받는 body 수정
Resolves: #183
어떤 변경 사항이 있나요?

[#183] FIX: 문의 게시판 오류 수정

---

api/src/main/java/org/silsagusi/api/customer/application/dto/CustomerExcelDto.java
api/src/main/java/org/silsagusi/api/customer/application/mapper/CustomerMapper.java
api/src/main/java/org/silsagusi/api/customer/application/parser/CustomerExcelParser.java
api/src/main/java/org/silsagusi/api/survey/application/service/SurveyService.java

customer parser에서 customer를 직접 만들기 때문에 mapper를 통해서 생성하도록 수정하였습니다
추가로 CustomerExcelDto를 만들어서 parser와 mapper사이를 이동하도록 하였습니다
Resolves: #195 
어떤 변경 사항이 있나요?

[#195] REFACTOR: customer의 parser - mapper 의존 추가

---

api/src/main/java/org/silsagusi/api/exception/handler/GlobalExceptionHandler.java
core/src/main/java/org/silsagusi/core/domain/customer/entity/Customer.java

customer를 만들 때 이름이나 전화번호가 중복이면 생성되지 않습니다
이 로직이 validator에서 동작하는데 db 레벨에서도 검증하기 위해 unique 제약조건을 추가하였습니다
Resolves: #198 
어떤 변경 사항이 있나요?

[#198] REFACTOR: customer 제약조건 추가

---

api/src/main/java/org/silsagusi/api/inquiry/application/dto/InquiryAnswerDto.java
api/src/main/java/org/silsagusi/api/notification/infrastructure/dataprovider/NotificationDataProvider.java

알림 중복 처리 시, 같은 사람이 여러 번 똑같은 행동을 했을 경우 알림이 안 가는 문제가 있어서 중복 처리 로직을 삭제했습니다
Resolves: #204
어떤 변경 사항이 있나요?

[#204] FIX: 알림 중복 처리 로직 삭제 

---

api/src/main/java/org/silsagusi/api/contract/infrastructure/dataprovider/ContractDataProvider.java
core/src/main/java/org/silsagusi/core/domain/contract/info/ContractDetailInfo.java
core/src/main/java/org/silsagusi/core/domain/contract/info/ContractInfo.java

계약 생성 시 url이 입력되지 않는 문제가 있어서 수정하였습니다
Resolves: #213
어떤 변경 사항이 있나요?

[#213] FIX: 계약 생성 시 url 오류 수정

---

api/src/main/java/org/silsagusi/api/auth/filter/JwtAuthorizationFilter.java

security config white list 추가
Resolves: #216 
어떤 변경 사항이 있나요?

[#216] FIX: security config white list 추가

---

batch/src/main/java/org/silsagusi/batch/job/NaverLandBatchJobConfig.java
batch/src/main/java/org/silsagusi/batch/job/ZigBangBatchJobConfig.java
batch/src/main/java/org/silsagusi/batch/naverland/application/NaverLandRequestService.java
batch/src/main/java/org/silsagusi/batch/scheduler/NaverLandScrapeScheduler.java
batch/src/main/java/org/silsagusi/batch/scheduler/ZigBangScrapeScheduler.java
batch/src/main/java/org/silsagusi/batch/zigbang/application/ZigBangRequestService.java
core/src/main/java/org/silsagusi/core/config/AsyncConfig.java
core/src/main/java/org/silsagusi/core/domain/article/ScrapeStatus.java

Batch 실행 중 API 요청 시 과도한 API 호출로 인해 NPE 발생하는 에러를 대응하였습니다.
Resolves: #218
어떤 변경 사항이 있나요?

[#218] FIX: Batch 모듈 NPE 대응

---

api/src/main/java/org/silsagusi/api/consultation/controller/ConsultationController.java

상담 상세 정보 조회 api 수정했습니다
Resolves: #215 
어떤 변경 사항이 있나요?

[#215] FIX: 상담 상세 정보 조회 api 수정

---

api/src/main/java/org/silsagusi/api/inquiry/controller/InquiryController.java
core/src/main/java/org/silsagusi/core/domain/inquiry/entity/Inquiry.java

문의게시판 답변 url 수정했습니다
Resolves: #226 
어떤 변경 사항이 있나요?

[#226] FIX: 문의게시판 답변 url 수정

---

api/src/main/java/org/silsagusi/api/notification/infrastructure/dataprovider/NotificationDataProvider.java

SSE 처리 중 에러 발생 시 로그 보기가 불편하여 sse error 로직 개선했습니다
Resolves: #228
어떤 변경 사항이 있나요?

[#228] REFACTOR: sse error 로직 개선

---

batch/src/main/java/org/silsagusi/batch/infrastructure/dataProvider/ArticleDataProvider.java
batch/src/main/java/org/silsagusi/batch/infrastructure/dataProvider/ComplexDataProvider.java
batch/src/main/java/org/silsagusi/batch/infrastructure/repository/ScrapeStatusRepository.java
batch/src/main/java/org/silsagusi/batch/job/NaverLandBatchJobConfig.java
batch/src/main/java/org/silsagusi/batch/job/ZigBangBatchJobConfig.java
batch/src/main/java/org/silsagusi/batch/naverland/application/NaverLandRequestService.java
batch/src/main/java/org/silsagusi/batch/scheduler/NaverLandScrapeScheduler.java
batch/src/main/java/org/silsagusi/batch/zigbang/application/ZigBangRequestService.java

기존에는 모든 scrape status를 불러와서 크롤링을 진행하다보니 오래 걸리는 문제가 있어서 10개씩만 조회하도록 수정하였습니다
Resolves: #233 
어떤 변경 사항이 있나요?

[#233] FIX: scrape status 조회 메소드 수정

---

api/src/main/java/org/silsagusi/api/common/auth/userDetails/CustomUserDetailsService.java

로그인 대소문자 구분하게 수정하였습니다
```
if (!agent.getUsername().equals(username)) {
throw new CustomException(ErrorCode.INVALID_CREDENTIALS);
}
```
Resolves: #238 
어떤 변경 사항이 있나요?

[#238] FIX: 로그인 대소문자 구분

---

api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ArticleRepository.java
api/src/main/java/org/silsagusi/api/consultation/infrastructure/repository/ConsultationRepository.java
api/src/main/java/org/silsagusi/api/contract/infrastructure/repository/ContractRepository.java
api/src/main/resources/application.yml
batch/src/main/java/org/silsagusi/batch/infrastructure/repository/ScrapeStatusRepository.java
core/src/main/java/org/silsagusi/core/domain/agent/Agent.java
core/src/main/java/org/silsagusi/core/domain/article/Article.java
core/src/main/java/org/silsagusi/core/domain/article/Complex.java
core/src/main/java/org/silsagusi/core/domain/article/Region.java
core/src/main/java/org/silsagusi/core/domain/article/ScrapeStatus.java
core/src/main/java/org/silsagusi/core/domain/consultation/entity/Consultation.java
core/src/main/java/org/silsagusi/core/domain/contract/entity/Contract.java
core/src/main/java/org/silsagusi/core/domain/customer/entity/Customer.java
core/src/main/java/org/silsagusi/core/domain/inquiry/entity/Inquiry.java
core/src/main/java/org/silsagusi/core/domain/inquiry/entity/InquiryAnswer.java
core/src/main/java/org/silsagusi/core/domain/message/entity/Message.java
core/src/main/java/org/silsagusi/core/domain/message/entity/MessageTemplate.java
core/src/main/java/org/silsagusi/core/domain/notification/entity/Notification.java
core/src/main/java/org/silsagusi/core/domain/survey/entity/Answer.java
core/src/main/java/org/silsagusi/core/domain/survey/entity/Question.java
core/src/main/java/org/silsagusi/core/domain/survey/entity/Survey.java

@Entity에 name속성을 주었는데 이게 테이블 이름을 정하는 것이 아니라 jpa에서 인식하는 이름을 바꾼다는 걸 알게 되었습니다
@Table을 추가하고 name 속성을 주었습니다
컬럼들 중 snake case와 camel case가 혼용되어 있어서 snake case로 통일하였습니다
Resolves: #241
어떤 변경 사항이 있나요?

[#241] REFACTOR: entity name 제거 및 table 추가

---

api/src/main/java/org/silsagusi/api/agent/controller/AgentController.java
api/src/main/java/org/silsagusi/api/message/controller/MessageController.java
api/src/main/java/org/silsagusi/api/survey/controller/SurveyController.java

RESTful 하게 API end point 수정하였습니다
Resolves: #243 
어떤 변경 사항이 있나요?

[#243] FIX: api endpoint 수정

---

api/src/main/java/org/silsagusi/api/common/auth/SecurityProperties.java
api/src/main/java/org/silsagusi/api/common/exception/handler/GlobalExceptionHandler.java
api/src/main/java/org/silsagusi/api/notification/application/service/NotificationService.java
api/src/main/java/org/silsagusi/api/notification/controller/NotificationController.java
api/src/main/java/org/silsagusi/api/notification/infrastructure/dataprovider/NotificationDataProvider.java
api/src/main/java/org/silsagusi/api/notification/infrastructure/repository/EmitterRepository.java

한 아이디로 접속한 여러 유저에게 모두 알람이 가도록 변경하였습니다.
ExceptionHandler에 SSE 객체는 처리 안하도록 예외를 추가했습니다.
RestFul하게 url을 변경하였습니다.
Resolves: #237
어떤 변경 사항이 있나요?

[#237] REFACTOR: 알림 로직 수정

---

api/src/main/java/org/silsagusi/api/agent/controller/AgentController.java
api/src/main/java/org/silsagusi/api/common/annotation/CurrentAgentId.java
api/src/main/java/org/silsagusi/api/common/config/WebConfig.java
api/src/main/java/org/silsagusi/api/common/util/CurrentAgentIdResolver.java
api/src/main/java/org/silsagusi/api/consultation/controller/ConsultationController.java
api/src/main/java/org/silsagusi/api/contract/controller/ContractController.java
api/src/main/java/org/silsagusi/api/customer/controller/CustomerController.java
api/src/main/java/org/silsagusi/api/inquiry/controller/InquiryController.java
api/src/main/java/org/silsagusi/api/message/controller/MessageController.java
api/src/main/java/org/silsagusi/api/message/controller/MessageTemplateController.java
api/src/main/java/org/silsagusi/api/notification/controller/NotificationController.java
api/src/main/java/org/silsagusi/api/survey/controller/SurveyController.java

헤더에서 agentId를 직접 빼서 쓰고 있는데 annotation을 만들어서 사용하도록 수정하였습니다
Resolves: #245 
어떤 변경 사항이 있나요?

[#245] REFACTOR: currentagentid 구현

---

api/src/main/java/org/silsagusi/api/notification/application/service/NotificationService.java
api/src/main/java/org/silsagusi/api/notification/controller/NotificationController.java
api/src/main/java/org/silsagusi/api/notification/infrastructure/dataprovider/NotificationDataProvider.java
api/src/main/java/org/silsagusi/api/notification/infrastructure/repository/EmitterRepository.java

notification에 생략된 save 추가했습니다
notificationId로 notification 1개를 가져오는 api 추가했습니다
알림 전송 전에 notification 객체를 만들어 DB 중복 저장 막았습니다
Resolves: #237
어떤 변경 사항이 있나요?

[#237] FEATURE: 알림 오류 수정

---

api/src/main/java/org/silsagusi/api/inquiry/application/service/InquiryService.java
api/src/main/java/org/silsagusi/api/inquiry/controller/InquiryController.java
api/src/main/java/org/silsagusi/api/inquiry/infrastructure/external/GeminiApiClient.java

WebClient로 받은 Mono객체를 바로 controller에서 보내고 있어
Mono가 아닌 Dto만으로 전달되도록 비동기 방식으로 변경했습니다
Resolves: #250
어떤 변경 사항이 있나요?

[#250] REFACTOR: webClient 비동기 방식으로 변경

---

api/src/main/java/org/silsagusi/api/customer/application/dto/CustomerExcelDto.java
api/src/main/java/org/silsagusi/api/customer/application/parser/CustomerExcelParser.java
core/build.gradle

엑셀 파일 지원 형식에 .xls 추가하고 cell 수정
및 오류 처리 추가했습니다
Resolves: #252
어떤 변경 사항이 있나요?

[#252] FEATURE: 엑셀 파일 지원 형식 추가 및 cell 수정

---

.github/workflows/cicd.yml

무중단 배포 설정 추가했습니다
Resolves: #256
어떤 변경 사항이 있나요?

[#256] REFACTOR: 무중단 배포 설정 추가

---

.gitignore
api/build.gradle
api/src/main/java/org/silsagusi/api/common/config/JpaConfig.java
api/src/main/java/org/silsagusi/api/contract/application/service/ContractService.java
api/src/main/java/org/silsagusi/api/contract/controller/ContractController.java
api/src/main/java/org/silsagusi/api/contract/infrastructure/dataprovider/ContractDataProvider.java
api/src/main/java/org/silsagusi/api/contract/infrastructure/repository/ContractCustomRepository.java
api/src/main/java/org/silsagusi/api/contract/infrastructure/repository/ContractCustomRepositoryImpl.java
api/src/main/java/org/silsagusi/api/contract/infrastructure/repository/ContractRepository.java
api/src/main/java/org/silsagusi/api/customer/application/dto/CustomerInfiniteResponse.java
api/src/main/java/org/silsagusi/api/customer/application/service/CustomerService.java
api/src/main/java/org/silsagusi/api/customer/controller/CustomerController.java
api/src/main/java/org/silsagusi/api/customer/infrastructure/dataprovider/CustomerDataProvider.java
api/src/main/java/org/silsagusi/api/customer/infrastructure/repository/CustomerCustomRepository.java
api/src/main/java/org/silsagusi/api/customer/infrastructure/repository/CustomerCustomRepositoryImpl.java
api/src/main/java/org/silsagusi/api/customer/infrastructure/repository/CustomerRepository.java
api/src/main/java/org/silsagusi/api/message/application/service/MessageService.java
api/src/main/java/org/silsagusi/api/message/controller/MessageController.java
api/src/main/java/org/silsagusi/api/message/infrastructure/dataProvider/MessageDataProvider.java
api/src/main/java/org/silsagusi/api/message/infrastructure/repository/MessageCustomRepository.java
api/src/main/java/org/silsagusi/api/message/infrastructure/repository/MessageCustomRepositoryImpl.java
api/src/main/java/org/silsagusi/api/message/infrastructure/repository/MessageRepository.java
core/build.gradle

고객, 계약, 문자, 설문 관리 페이지의 조회방식을 무한스크롤에서 페이지네이션으로 변경하였습니다(+이부분은 프론트만 수정하였습니다)
계약 등록, 상담 등록, 문자 예약 페이지에서 고객 조회할 때 Pageable->Page였는데, 무한스크롤에 불필요한 과정이 있어서 cursor->Slice방식으로 변경하였습니다
키워드 기반 검색을 위해 QueryDSL을 도입하였습니다
Resolves: #257 
어떤 변경 사항이 있나요?

[#257] REFACTOR: 페이지네이션 리팩토링

---

batch/src/main/java/org/silsagusi/batch/job/common/AutoRestartJobListener.java
batch/src/main/java/org/silsagusi/batch/job/naverland/NaverLandArticleStepConfig.java
batch/src/main/java/org/silsagusi/batch/job/naverland/NaverLandComplexStepConfig.java
batch/src/main/java/org/silsagusi/batch/job/naverland/NaverLandJobConfig.java
batch/src/main/java/org/silsagusi/batch/job/zigbang/ZigbangArticleStepConfig.java
batch/src/main/java/org/silsagusi/batch/job/zigbang/ZigbangComplexStepConfig.java
batch/src/main/java/org/silsagusi/batch/job/zigbang/ZigbangJobConfig.java
batch/src/main/java/org/silsagusi/batch/naverland/application/NaverLandScraper.java
batch/src/main/java/org/silsagusi/batch/zigbang/application/ZigbangScraper.java
batch/src/main/java/org/silsagusi/batch/zigbang/infrastructure/dto/ZigBangDanjiResponse.java
core/src/main/java/org/silsagusi/core/domain/article/ScrapeStatus.java
core/src/main/java/org/silsagusi/core/domain/article/enums/ScrapeStatusType.java

배치 잡의 순서를 변경하였습니다
Resolves: #265 
어떤 변경 사항이 있나요?

[#265] FIX: 배치 잡 순서 변경

---

api/src/main/java/org/silsagusi/api/notification/infrastructure/dataprovider/NotificationDataProvider.java

SSE 첫 연결 확인 시 보내는 데이터의 MediaType을 제거하여, 알림 전송 잘 되는지 확인했습니다
Resolves: #263
어떤 변경 사항이 있나요?

[#263] FIX: SSE 첫 연결 확인 MediaType 제거

---

.github/workflows/cicd.yml

테스트 코드 자동 실행 및 결과 PR 코멘트 자동 등록 기능 추가
Resolves: #270
어떤 변경 사항이 있나요?

[#270] CHORE: 테스트 코드 자동 실행 및 결과 PR 코멘트 자동 등록 기능 추가

---

api/src/test/java/org/silsagusi/api/notification/application/service/NotificationServiceTest.java

알림 오류가 많이 발생해 subscribe, notify test code 추가했습니다
Resolves: #270
어떤 변경 사항이 있나요?

[#270] TEST: subscribe, notify test code 추가

---

api/src/main/java/org/silsagusi/api/article/application/assembler/ArticleListModelAssembler.java
api/src/main/java/org/silsagusi/api/article/application/assembler/ArticleModelAssembler.java
api/src/main/java/org/silsagusi/api/article/application/assembler/ClusterModelAssembler.java
api/src/main/java/org/silsagusi/api/article/application/mapper/ComplexMapper.java
api/src/main/java/org/silsagusi/api/article/application/service/ArticleService.java
api/src/main/java/org/silsagusi/api/article/application/validator/ArticleValidator.java
api/src/main/java/org/silsagusi/api/article/controller/ArticleController.java
api/src/main/java/org/silsagusi/api/article/controller/request/ArticleListRequest.java
api/src/main/java/org/silsagusi/api/article/controller/request/ArticleSearchCriteria.java
api/src/main/java/org/silsagusi/api/article/controller/request/ClusterRequest.java
api/src/main/java/org/silsagusi/api/article/infrastructure/dataprovider/ArticleDataProvider.java
api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ArticleCustomRepository.java
api/src/main/java/org/silsagusi/api/article/infrastructure/repository/ArticleCustomRepositoryImpl.java

매물 응답값을 Spring HATEOAS 적용했습니다.
Resolves: #281
어떤 변경 사항이 있나요?

[#281] FEAT: Spring HATEOAS 응답처리

---

api/build.gradle
batch/build.gradle
build.gradle
core/build.gradle
core/src/test/java/org/silsagusi/core/CoreApplicationTests.java

./gradlew clean build 실행을 위해 모듈별 build.gradle 최적화를 했습니다.
Resolves: #288
어떤 변경 사항이 있나요?

[#288] REFACT: build.gradle 최적화

---

batch/src/main/java/org/silsagusi/batch/infrastructure/dataprovider/ScrapeStatusDataProvider.java
batch/src/main/java/org/silsagusi/batch/job/common/ArticleAddressStepConfig.java
batch/src/main/java/org/silsagusi/batch/job/common/ScrapeJobStarter.java
batch/src/main/java/org/silsagusi/batch/job/naverland/NaverLandArticleStepConfig.java
batch/src/main/java/org/silsagusi/batch/job/naverland/NaverLandComplexStepConfig.java
batch/src/main/java/org/silsagusi/batch/job/zigbang/ZigbangArticleStepConfig.java
batch/src/main/java/org/silsagusi/batch/job/zigbang/ZigbangComplexStepConfig.java
batch/src/main/java/org/silsagusi/batch/naverland/application/NaverLandScraper.java
batch/src/main/java/org/silsagusi/batch/zigbang/application/ZigbangScraper.java
batch/src/main/java/org/silsagusi/batch/zigbang/infrastructure/ZigBangApiClient.java
core/src/main/java/org/silsagusi/core/domain/article/ScrapeStatus.java
core/src/main/java/org/silsagusi/core/domain/article/enums/ScrapeStatusType.java

기존에는 tasklet기반으로 모든 지역에 대해서 커넥션 1개로 진행했는데 chunk단위로 변경하여 지역1개당 커넥션 1개로 진행하도록 변경하였습니다
Resolves: #284 
어떤 변경 사항이 있나요?

[#285] REFACTOR: tasklet -> chunk기반으로 변경

---

api/src/main/java/org/silsagusi/api/common/auth/filter/JwtAuthorizationFilter.java
api/src/main/java/org/silsagusi/api/common/auth/jwt/JwtProvider.java
api/src/main/java/org/silsagusi/api/common/exception/CustomException.java
api/src/main/java/org/silsagusi/api/common/exception/handler/CustomAccessDeniedHandler.java
api/src/main/java/org/silsagusi/api/common/exception/handler/CustomAuthenticationEntryPointHandler.java

토큰 재발급 로직 수정하고 시간도 15분으로 설정하였습니다
Resolves: #290
어떤 변경 사항이 있나요?

[#290] FIX: 토큰 재발급 로직 수정
